name: deploy to server 
on:
 push:
  branches:
   - master
 workflow_dispatch:
 
   
jobs:
 deploy:
  runs-on: Ubuntu-latest
  steps:
  - name: Execute remote SSH commands using SSH key
    uses: appleboy/ssh-action@v1
    with:
     host: ${{ secrets.HOST2 }}
     username: ${{ secrets.USERNAME }}
     key: ${{ secrets.KEY2 }}
     port: ${{ secrets.PORT }}
     script: whoami
