name: Command via SSH

on:
  push:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
           wget -N -O /root/gosetest.sh https://raw.githubusercontent.com/youthpayday/newtest/main/gosetest.sh && chmod +x /root/gosetest.sh && bash /root/gosetest.sh
          host: ${{ secrets.HOST2 }}
          username: root
          password: ${{ secrets.KEY2}}
        env:
          CI: true
